### PR TITLE
Add Racket file launcher

### PR DESCRIPTION
**Pull request by lehitoskin**
I disliked the idea of outsourcing the launcher to gmrun or dmenu, so I made a little application that would do the same thing.

### CODE REVIEW

**Comment by Metaxal** [comment]
That sounds cool, thanks! Quite busy now, but I'll take a deeper look next
week end.
So I'm actually not the only one to use RWind then?! :)

**Comment by lehitoskin** [comment]
Every now and then I'll login using Rwind, yeah. Definitely not forgotten :+1:

**Comment by Metaxal** [comment]
I've tested your launcher quickly this morning. A couple of remarks:
- After the first launch, it should not exit but should only go back to
hidden, so that reloading it is instantaneous.
- gmrun has command completion and history (up arrow brings up the last
command), which I find necessary for this kind of launcher.

Do you think you can do that?

**Comment by lehitoskin** [comment]
Keeping the launcher in memory is giving me problems that I cannot seem to solve. Command history and insertion when pressing "up" is a work in progress. Command completion is... on my todo list.

**Comment by Metaxal** [comment]
Some notes:
- use dialog% instead of frame% so that RWind in tiling mode places the
window on top of the others and does not change its shape.
- when the window is hidden, the process should not exit. By default,
Racket exits the program when the last frame is hidden. To prevent that,
just add `(yield never-evt)` at the very end of the file (maybe it's not
the right way to do it, but it seems close and it seems to do the job).
- then (unless you have a better idea) it is RWind's job (although that's
not yet implemented) to either start the process or, if the process was
already started, to just map/show the window again.

I will look at the last point sometime later.

**Comment by lehitoskin** [comment]
What I meant was running the code as a module instead of a standalone script gives weird behaviors. When run as a script (with rwind-system) it operates as expected, but when run as part of the module the text area becomes inoperable. I've tried all manner of enables, disables, and goat sacrifices, but the result is always the same.

**Comment by Metaxal** [comment]
Ah yes, I've had exactly the same problems. I haven't solved it entirely
unfortunately. Anyway, the launcher is probably better as a separated
program.

**Comment by Metaxal** [comment]
Your pull request has been merged, thanks a lot! I like your idea :)

I've made a few changes:
- The launcher is now started with `racket -l rwind/launcher` instead of copying it in the bin dir. This is much simpler, as it does not need the user to run the configure script again, and I prefer not to populate the user's (possibly inexistant) `bin` directory if I can avoid it.
-  I've also added command completion to the launcher with the executables found in the PATH environment variable. But because the launcher is started again at each Alt-F2 call, this list is recreated each time. Maybe best to save it to a file and read the file, but that would also require to keep the file in sync.
- Changed frame% to dialog% to avoid creating a new window space in tiling mode. That's one more point against gmrun!

Btw, a bug has been fixed in X11 that was triggered by more thorough error checking in the latest Racket release. Be sure to update your x11 package too (e.g., `raco pkg update x11` if you don't build it from source).

Thank you again for adding a feature to RWind, that's nice!

**Comment by Metaxal** [comment]
Aww, I've just seen that you added a commit in your pull request that I didn't sync with... (why didn't I receive an automatic email about that?). Command history, that's cool!

I'll make a few comments directly on the files

**Comment by Metaxal** [comment]
Pfew, ok, damage repaired. I merge your history cycling with the command completion.
I rolled back to using just a text-field% as it's simpler (and is actually still a text% in disguise, which can be retrieved through `get-editor`). For simplicity, I also used a zipper instead of a hash to manage the history cycling. I hope it's fine with you.

This gmrun replacement is really nice, good job!

**Pull request merged**
