### PR TITLE
configure.rkt: create ~/.config/rwind before copying files

### LINKED ISSUE #19: rwind/configure fails if ~/.config/rwind doesn't exist
Suggestion: create the needed directories recursively.

image

### PR DESCRIPTION
**Pull request by xgqt**
closes: https://github.com/Metaxal/rwind/issues/19

Signed-off-by: Maciej Barć <xgqt@protonmail.com>

### CODE REVIEW

**Comment by Metaxal** [comment]
Thanks for this. I'll do something a little more general. But while trying this out, it appears that RWind now fails for several other reason. I'm not even sure how you managed to make it work! (working on it, obviously)

**Comment by xgqt** [comment]
> Thanks for this. I'll do something a little more general. But while trying this out, it appears that RWind now fails for several other reason. I'm not even sure how you managed to make it work! (working on it, obviously)

I just cloned the repo, did my mods and `raco pkg install`, maybe my links.rktd was messed up but I doubt it... 

Anyway this change seems trivial to me

**Comment by Metaxal** [comment]
Ok, that makes sense then. I'm going to make it work again for me at least, and if you're willing to try a little harder after that I'd be happy to receive your feedback.

**Comment by Metaxal** [comment]
This is fixed in this commit:
https://github.com/Metaxal/rwind/commit/374849a765dd3d1e7aecc87d06349cc852ec8648
so I'm closing this PR.

Thank you very much in any case for proposing a solution!

**Comment by Metaxal** [comment]
I've enhanced the installation process. If you try rwind again, please let me know how that goes, thanks!

**Pull request closed without merging**
